export enum GameState {
  Boot = 'Boot',
  CheckHotUpdate = 'CheckHotUpdate',
  DownloadHotUpdate = 'DownloadHotUpdate',
  RestartRequired = 'RestartRequired',
  LoadConfig = 'LoadConfig',
  Login = 'Login',
  Hall = 'Hall',
  SubGameLoading = 'SubGameLoading',
  SubGameRunning = 'SubGameRunning',
  SubGameSettlement = 'SubGameSettlement',
  Home = 'Home',
  Battle = 'Battle',
  Settlement = 'Settlement',
}
